Bug fix: Using single examplar create any number of core instances no longer limited to number of coreX examplars present

diff --git a/bin/esg-search b/bin/esg-search
--- a/bin/esg-search
+++ b/bin/esg-search
@@ -622,12 +622,19 @@ setup_solr() {
 
     [ -d ${solr_install_dir} ] && (echo "Backing up previous install... " && (backup ${solr_install_dir} || (mv ${solr_install_dir}{,.bak} || echo "Could not move aside prev install")))
     cp -R ${solr_dist_dir}/example ${solr_install_dir}
+    rm -rf ${solr_install_dir}/multicore/core*
+    local err_count=0
     for ((i=0;i<${#solr_cores[@]};i++)) ; do
-        [ -e ${solr_install_dir}/multicore/core${i} ] && mv -v ${solr_install_dir}/multicore/{core${i},${solr_cores[${i}]}}
+        if [ -e ${solr_install_dir}/example/multicore/core0 ]; then
+            cp -R ${solr_install_dir}/example/multicore/core0 ${solr_install_dir}/multicore/${solr_cores[${i}]}
+            [ $? !=0 ] && echo "Could not install core: ${solr_cores[${i}]} - no exemplar found" && ((err_count++)) && continue
+        fi
+
         #special files needed to complete the configuration...
         cp ${solr_workdir}/apache-solr-${solr_version}/example/solr/conf/{stopwords.txt,synonyms.txt,protwords.txt,elevate.xml} ${solr_install_dir}/multicore/${solr_cores[${i}]}/conf/
+        echo "Installed core: ${solr_cores[${i}]} - [OK]"
     done
-    #rm -rf ${solr_install_dir}/multicore/exampledocs
+    rm -rf ${solr_install_dir}/multicore/exampledocs
     echo "${solr_version}" > ${solr_install_dir}/VERSION
 
 
@@ -636,8 +643,10 @@ setup_solr() {
     chown -R ${installer_uid}:${installer_gid} $(readlink -f ${solr_install_dir})
     
     popd >& /dev/null
-    echo "esgf-solr setup [OK]"
-    return 0
+    echo -n "esgf-solr setup "
+    (( err_count == 0 )) && echo "[OK]" && return 0
+    (( (err_count > 0) && (err_count < ${#solr_cores[@]}) )) && echo "[PARTIAL]" && return 1
+    (( err_count == ${#solr_cores[@]} )) && echo "[FAIL]" && return 2
 }
 
 #Helper Method to figure out the version of esgf-solr installation
