esg-search install script: zookeeper install initial edit

diff --git a/bin/esg-search b/bin/esg-search
--- a/bin/esg-search
+++ b/bin/esg-search
@@ -69,11 +69,22 @@
 #              ${workdir}, etc....
 
 
+esg_dist_url=http://198.128.245.140/dist
+
+install_prefix=${install_prefix:-"/usr/local"}
+esg_root_dir=${esg_root_dir:-"/esg"}
+workdir=${workdir:-~/workbench/esg}
 install_logfile=${ESG_INSTALL_LOGFILE:-"/etc/esg.install_log"}
 date_format=${date_format:-"+%Y_%m_%d_%H%M%S"}
-search_version=${drslib_version:-"1.0.0.0"}
-search_install_dir=${search_install_dir:-""}
 
+search_version=${search_version:-"1.0.0.0"}
+search_install_dir=${ESGF_INSTALL_DIR:-"${install_prefix}/esgf_search"}
+seach_data_dir=${ESGF_DATA_DIR:="${esg_root_dir}/search_data"}
+
+
+#---------------------------------------------------------
+# The "main" method for this script
+#---------------------------------------------------------
 #arg (1) - install = 0 [default]
 #          upgrade = 1 
 setup_search() {
@@ -85,15 +96,216 @@ setup_search() {
 
     local upgrade=${1:-0}
 
-    //Do the installation stuff that you need to do here.    
+    setup_zookeeper && configure_zookeeper && write_zookeeper_install_log
+    [ $? != 0 ] && echo " ERROR: Could not fully install zookeeper :-( "
 
-    write_search_install_log
+    #setup_solr && configure_solr && write_solr_install_log
+    #[ $? != 0 ] && echo " ERROR: Could not fully install solr :-( "
+    #
+    #write_search_install_log
+
     echo "done"
     return 0
 }
 
 write_search_install_log() {
-    echo "$(date ${date_format}) webapp:esg-search=${search_version} ${search_install_dir}" >> ${install_logfile}
+    echo "$(date ${date_format}) esg-search=${search_version} ${search_install_dir}" >> ${install_logfile}
     dedup ${install_logfile}
     return 0
+}
+
+#---------------------------------------------------------
+# Zookeeper Setup and Configuration
+#---------------------------------------------------------
+zookeeper_version="3.3.1"
+zookeeper_dist_url=http://apache.osuosl.org//hadoop/zookeeper/zookeeper-${zookeeper_version}/zookeeper-${zookeeper_version}.tar.gz
+zookeeper_workdir=${workdir}/zookeeper
+zookeeper_install_dir=${install_prefix}/zookeeper
+zookeeper_data_dir=${esg_root_dir}/zookeeper
+zookeeper_client_port=2181
+
+setup_zookeeper() {
+
+    #TODO... put in zookeeper install check
+    
+    echo "Installing zookeeper v${zookeeper_version}"
+    mkdir -p ${zookeeper_workdir}
+    pushd ${zookeeper_workdir} >& /dev/null
+
+    local zookeeper_dist_file=${zookeeper_dist_url##*/}
+    local zookeeper_dist_dir=$(echo ${zookeeper_dist_file} | awk 'gsub(/('$compress_extensions')/,"")')
+
+    #There is this pesky case of having a zero sized dist file... WTF!?
+    if [ -e ${zookeeper_dist_file} ]; then
+        ls -l ${zookeeper_dist_file}
+        local size=$(stat -c%s ${zookeeper_dist_file})
+        (( size == 0 )) && rm -v ${zookeeper_dist_file}
+    fi
+
+    #Check to see if we already have a zookeeper distribution directory
+    if [ ! -e ${zookeeper_install_dir%/*}/${zookeeper_dist_dir} ]; then
+        echo "Don't see zookeeper distribution dir ${zookeeper_install_dir%/*}/${zookeeper_dist_dir}"
+        if [ ! -e ${zookeeper_dist_file} ]; then
+            echo "Don't see zookeeper distribution file $(pwd)/${zookeeper_dist_file} either"
+            echo "Downloading zookeeper from ${zookeeper_dist_url}"
+            wget -O ${zookeeper_dist_file} ${zookeeper_dist_url}
+            [ $? != 0 ] && echo " ERROR: Could not download zookeeper ${zookeeper_dist_file}" && popd && checked_done 1
+            echo "unpacking ${zookeeper_dist_file}... into ${zookeeper_install_dir%/*}"
+            tar xzf ${zookeeper_dist_file} -C ${zookeeper_install_dir%/*}
+            [ $? != 0 ] && echo " ERROR: Could not extract zookeeper :-( " && popd && checked_done 1
+        fi
+    fi
+    
+    #If you don't see the directory but see the tar.gz distribution
+    #then expand it and go from there....
+    if [ -e ${zookeeper_dist_file} ] && [ ! -e ${zookeeper_install_dir%/*}/${zookeeper_dist_dir} ]; then
+        echo "unpacking* ${zookeeper_dist_file} into ${zookeeper_install_dir%/*}"
+        tar xzf ${zookeeper_dist_file} -C ${zookeeper_install_dir%/*}
+        [ $? != 0 ] && echo " ERROR: Could not extract zookeeper :-( " && popd && checked_done 1
+    fi
+
+    if [ ! -e ${zookeeper_install_dir} ]; then
+        ln -s ${zookeeper_install_dir%/*}/${zookeeper_dist_dir} ${zookeeper_install_dir}
+        [ $? != 0 ] && \
+            echo " ERROR: Could not create sym link ${zookeeper_install_dir%/*}/${zookeeper_dist_dir} -> ${zookeeper_install_dir}" && popd && checked_done 1
+    else
+        unlink ${zookeeper_install_dir}
+        [ $? != 0 ] && mv ${zookeeper_install_dir} ${zookeeper_install_dir}.$(date ${date_format}).bak
+        
+        ln -s ${zookeeper_install_dir%/*}/${zookeeper_dist_dir} ${zookeeper_install_dir}
+        [ $? != 0 ] && \
+            echo " ERROR*: Could not create sym link ${zookeeper_install_dir%/*}/${zookeeper_dist_dir} -> ${zookeeper_install_dir}" && popd && checked_done 1
+    fi
+    (($DEBUG)) && echo "chown -R ${installer_uid}:${installer_gid} ${java_install_dir}"
+    chown    ${installer_uid}:${installer_gid} ${zookeeper_install_dir}
+    chown -R ${installer_uid}:${installer_gid} $(readlink -f ${zookeeper_install_dir})
+    
+    popd >& /dev/null
+    echo "zookeeper setup [OK]"
+    return 0
+}
+
+configure_zookeeper() {
+    pushd ${zookeeper_install_dir}
+    export ZK_DIR=${zookeeper_install_dir} #NOTE: Is this a special variable used by zookeeper? If not get rid of line.
+
+    sed "s:/tmp/zookeeper:${zookeeper_install_dir}:" <(curl -s -L --insecure ${esg_dist_url}/zoo.cfg) > ${zookeeper_install_dir}/conf/zoo.cfg
+    cat ${zookeeper_install_dir}/conf/zoo.cfg
+    mkdir -p ${zookeeper_data_dir}
+    
+    sha1sum <(echo esgf$(hostname -i)) | awk '{print $1}' > ${zookeeper_data_dir}/myid
+    echo "zookeeper id: $(cat ${zookeeper_data_dir}/myid)"
+    popd >& /dev/null
+    echo "zookeeper configuration [OK]"
+    return 0
+}
+
+test_zookeeper() {
+    #test client connection
+    ${zookeeper_install_dir}/bin/zkCli.sh -server localhost:2181 ls / quit
+}
+
+write_zookeeper_install_log() {
+    local entry="$(date ${date_format}) esg-search:zookeeper=${zookeeper_version} ${zookeeper_install_dir}"
+    echo ${entry} >> ${install_logfile}
+    dedup ${install_logfile}
+    return 0
+}
+
+start_zookeeper() {
+    #start server (client port: 2181)
+    echo -n "Starting zookeeper server on port ${zookeeper_client_port}"
+
+    ${zookeeper_install_dir}/bin/zkServer.sh start
+    
+    #Don't wait 10 seconds if you don't have to...
+    #just check every second up till 10 seconds (or <= 10x)
+    local wait_time=10
+    local ret=1
+    while [[ $wait_time > 0 ]]; do
+        netstat -na | grep -i ${zookeeper_client_port}
+        ret=$?
+        [ $ret == 0 ] && break
+        sleep 1
+        ((wait_time--))
+        echo -n "."
+    done
+    [ $ret == 0 ] && echo " [OK]" || echo " [FAIL]"
+    return $ret
+}
+
+stop_zookeeper() {
+    ${zookeeper_install_dir}bin/zkServer.sh stop
+}
+#---------------------------------------------------------
+
+
+
+#---------------------------------------------------------
+# Solr/Lucene Setup and Configuration
+#---------------------------------------------------------
+setup_solr() {
+# installation
+    cd $ESGF_INSTALL_DIR
+    cp $ESGF_SOURCE_DIR/solr/esgf-solr-cloud.tar.gz .
+    tar xvfz esgf-solr-cloud.tar.gz
+    export SOLR_DIR=$ESGF_INSTALL_DIR/esgf-solr-cloud
+    
+# configuration
+    cp $ESGF_SOURCE_DIR/solr/solrconfig.xml $SOLR_DIR/solr/conf/.
+    cp $ESGF_SOURCE_DIR/solr/schema.xml $SOLR_DIR/solr/conf/.
+    sed "s:@@myid@@:$ZKID:" < $ESGF_SOURCE_DIR/solr/solr.xml > $SOLR_DIR/solr/solr.xml
+    cat $SOLR_DIR/solr/solr.xml
+    
+# start Solr server on port 8983 connecting to Zookeeper on port 2181
+    cd esgf-solr-cloud
+    java -Dbootstrap_confdir=./solr/conf -Dcollection.configName=esgf-conf -DzkHost=localhost:2181 -jar start.jar &
+    
+# check server port
+    netstat -na | grep -i 8983
+    
+}
+
+stop_search_services() {
+    
+# stop Solr server
+    pid=`/usr/sbin/lsof -i:8983 | grep -i java | awk '{print $2}'`
+    kill -9 $pid
+    
+# stop ZK server
+    $ESGF_INSTALL_DIR/zookeeper/bin/zkServer.sh stop
+    
+}
+
+setup_search_tomcat() {
+# installation
+    cd $ESGF_INSTALL_DIR
+    cp $ESGF_SOURCE_DIR/tomcat/apache-tomcat-6.0.26.tar .
+    tar xvf apache-tomcat-6.0.26.tar
+    ln -s ./apache-tomcat-6.0.26 ./apache-tomcat
+    
+# esgf-web-fe
+    export WEB_APP_DIR=$ESGF_INSTALL_DIR/apache-tomcat/webapps/esg-web
+    mkdir $WEB_APP_DIR
+    cp $ESGF_SOURCE_DIR/esg-web-fe/esg-search-web.war $WEB_APP_DIR/esg-web.war
+    cd $WEB_APP_DIR
+    jar xvf $WEB_APP_DIR/esg-web.war
+    
+# start
+    export CATALINA_HOME=$ESGF_INSTALL_DIR/apache-tomcat
+    export CATALINA_BASE=$ESGF_INSTALL_DIR/apache-tomcat
+    $CATALINA_BASE/bin/catalina.sh start
+    
+# check server port
+    sleep 10
+    netstat -na | grep -i 8080
+    
+    
+}
+
+test_search() {
+# publish test catalog
+    cd $WEB_APP_DIR
+    java -Dlog4j.configuration=./WEB-INF/classes/log4j.xml -Djava.ext.dirs=./WEB-INF/lib esg.search.publish.impl.PublishingServiceMain file://$ESGF_TESTDATA_DIR/pcmdi.ipcc4.GFDL.gfdl_cm2_0.picntrl.mon.land.run1.v1.xml THREDDS true
+
 }
