solr_config() completes.

diff --git a/bin/esg-search b/bin/esg-search
--- a/bin/esg-search
+++ b/bin/esg-search
@@ -828,8 +828,8 @@ check_solr_version() {
 configure_solr() {
     solr_init ${1} >& /dev/null
     echo -n "Configuring solr... ${solr_config_type} port[${solr_server_port}] "
-    pushd ${solr_install_dir}/solr/collection1/conf >& /dev/null
-    [ $? != 0 ] && echo "Could not locate directory ${solr_install_dir}/solr/conf :-( " && return 1
+    #pushd ${solr_install_dir}/solr/collection1/conf >& /dev/null
+    #[ $? != 0 ] && echo "Could not locate directory ${solr_install_dir}/solr/conf :-( " && return 1
 
     local suffix
     if [ "${solr_config_type}" = "master" ] || [ "${solr_config_type}" = "slave" ]; then
@@ -839,29 +839,31 @@ configure_solr() {
     fi
 
     #------------------------
+    # OBSOLETE
     #Setting up solrconfig.xml file for all cores
     #------------------------
     # Modify the solrconfig.xml file in *each* of the cores' dir tree to reflect remote.
-    for ((i=0;i<${#solr_cores[@]};i++)); do
-        echo -n "*"
-        verbose_print "curl -s -L --insecure ${esg_dist_url}/esg-search/solrconfig.xml$([ "${suffix}" = "replica" ] && echo "-${suffix}" || echo "") > ${solr_install_dir}/multicore/${solr_cores[${i}]}/conf/solrconfig.xml"
-        curl -s -L --insecure ${esg_dist_url}/esg-search/solrconfig.xml$([ "${suffix}" = "replica" ] && echo "-${suffix}" || echo "") > ${solr_install_dir}/multicore/${solr_cores[${i}]}/conf/solrconfig.xml
-        [ $? != 0 ] && echo && echo "Problem configuring (config) solr for ${solr_cores[${i}]} (2)" && return 3
-        chmod 755 ${solr_install_dir}/multicore/${solr_cores[${i}]}/conf/solrconfig.xml
-        if [ "${suffix}" = "replica" ]; then
-            sed -i 's#\(.*masterUrl.*http://\)\(.*\)\(:'${index_slave_port}'.*\)#\1'${solr_config_type}'\3#' ${solr_install_dir}/multicore/${solr_cores[${i}]}/conf/solrconfig.xml
-        fi
-    done
+    #for ((i=0;i<${#solr_cores[@]};i++)); do
+    #    echo -n "*"
+    #    verbose_print "curl -s -L --insecure ${esg_dist_url}/esg-search/solrconfig.xml$([ "${suffix}" = "replica" ] && echo "-${suffix}" || echo "") > ${solr_install_dir}/multicore/${solr_cores[${i}]}/conf/solrconfig.xml"
+    #    curl -s -L --insecure ${esg_dist_url}/esg-search/solrconfig.xml$([ "${suffix}" = "replica" ] && echo "-${suffix}" || echo "") > ${solr_install_dir}/multicore/${solr_cores[${i}]}/conf/solrconfig.xml
+    #    [ $? != 0 ] && echo && echo "Problem configuring (config) solr for ${solr_cores[${i}]} (2)" && return 3
+    #    chmod 755 ${solr_install_dir}/multicore/${solr_cores[${i}]}/conf/solrconfig.xml
+    #    if [ "${suffix}" = "replica" ]; then
+    #        sed -i 's#\(.*masterUrl.*http://\)\(.*\)\(:'${index_slave_port}'.*\)#\1'${solr_config_type}'\3#' ${solr_install_dir}/multicore/${solr_cores[${i}]}/conf/solrconfig.xml
+    #    fi
+    #done
 
     #------------------------
+    # OBSOLETE
     #Setting up schema.xml file for all cores
     #------------------------
-    for ((i=0;i<${#solr_cores[@]};i++)); do
-        verbose_print "curl -s -L --insecure ${esg_dist_url}/esg-search/schema.xml > ${solr_install_dir}/multicore/${solr_cores[${i}]}/conf/schema.xml"
-        curl -s -L --insecure ${esg_dist_url}/esg-search/schema.xml > ${solr_install_dir}/multicore/${solr_cores[${i}]}/conf/schema.xml
-        [ $? != 0 ] && echo && echo "Problem configuring solr for ${solr_cores[${i}]} (3)" && return 3
-        chmod 755 ${solr_install_dir}/multicore/${solr_cores[${i}]}/conf/schema.xml
-    done
+    #for ((i=0;i<${#solr_cores[@]};i++)); do
+    #    verbose_print "curl -s -L --insecure ${esg_dist_url}/esg-search/schema.xml > ${solr_install_dir}/multicore/${solr_cores[${i}]}/conf/schema.xml"
+    #    curl -s -L --insecure ${esg_dist_url}/esg-search/schema.xml > ${solr_install_dir}/multicore/${solr_cores[${i}]}/conf/schema.xml
+    #    [ $? != 0 ] && echo && echo "Problem configuring solr for ${solr_cores[${i}]} (3)" && return 3
+    #    chmod 755 ${solr_install_dir}/multicore/${solr_cores[${i}]}/conf/schema.xml
+    #done
 
     #------------------------
     #Create the data (index) directories
@@ -870,6 +872,7 @@ configure_solr() {
     chown -R ${installer_uid}:${installer_gid} $(readlink -f ${solr_data_dir})
 
     #------------------------
+    # OBSOLETE
     # FOR THE SLAVE ONLY, override the Jetty files with new ones that support authentication:
     #	- cp esg-search/etc/conf/jetty/jetty.xml-auth --> /usr/local/esgf-solr-3.1.0-slave/etc/jetty.xml
     #	- cp esg-search/etc/conf/jetty/realm.properties /usr/local/esgf-solr-3.1.0-slave/etc/.
@@ -897,14 +900,14 @@ configure_solr() {
         #_add_myself_to_distrib_shards_list ${solr_install_dir}/solr/conf/solrconfig.xml
      #fi
 
-    _curl "${esg_dist_url}/esg-search/solr.xml-${suffix}" "${solr_install_dir}/multicore/solr.xml" || checked_done 1
+    #_curl "${esg_dist_url}/esg-search/solr.xml-${suffix}" "${solr_install_dir}/multicore/solr.xml" || checked_done 1
     
     #Just editing the single file solr.xml but multiple times (one for each core)
-    for ((i=0;i<${#solr_cores[@]};i++)) ; do
-        sed -i 's#\(.*<core.*dataDir="\)\([a-zA-Z@/-]*\)\(\/\('${solr_cores[i]}'\).*\)#\1'${solr_data_dir}'\3#' ${solr_install_dir}/multicore/solr.xml
-        [ $? != 0 ] && echo && echo "Problem configuring (solr.xml) solr for ${solr_config_type} wth core = [${solr_cores[i]}]  (2)" && return 3
-    done
-    chmod 755 ${solr_install_dir}/multicore/solr.xml
+    #for ((i=0;i<${#solr_cores[@]};i++)) ; do
+    #    sed -i 's#\(.*<core.*dataDir="\)\([a-zA-Z@/-]*\)\(\/\('${solr_cores[i]}'\).*\)#\1'${solr_data_dir}'\3#' ${solr_install_dir}/multicore/solr.xml
+    #    [ $? != 0 ] && echo && echo "Problem configuring (solr.xml) solr for ${solr_config_type} wth core = [${solr_cores[i]}]  (2)" && return 3
+    #done
+    #chmod 755 ${solr_install_dir}/multicore/solr.xml
 
     popd >& /dev/null
     echo " [OK]"
