Enabling esg-node --remove-replica-shard

diff --git a/bin/esg-search b/bin/esg-search
--- a/bin/esg-search
+++ b/bin/esg-search
@@ -433,8 +433,8 @@ _remove_replica_shard_configuration() {
     local pid
     if pid=$(pgrep -f jetty.port=${solr_server_port}); then
         echo -n "Stopping index procees for this shard ${remote_host} [pid = ${pid}] "
-        kill -9 ${pid}
-        pgrep -f jetty.port=${solr_server_port} >& /dev/null && echo "[FAIL] - unable to kill index proecess on port ${solr_server_port}" || echo "[OK] "
+        ${solr_server_dir}/bin/solr stop -p ${solr_server_port}
+        pgrep -f jetty.port=${solr_server_port} >& /dev/null && echo "[FAIL] - unable to stop solr server on port ${solr_server_port}" || echo "[OK] "
     else
         echo "no process found for [pid = ${pid}] "
     fi
