Added zookeeper install check

diff --git a/bin/esg-search b/bin/esg-search
--- a/bin/esg-search
+++ b/bin/esg-search
@@ -114,6 +114,19 @@ write_search_install_log() {
     return 0
 }
 
+start_search_services() {
+    echo "Starting search services..."
+}
+
+stop_search_services() {
+    echo "Stopping search services..."
+}
+
+test_search_services() {
+    echo "Testing search services..."
+
+}
+
 #---------------------------------------------------------
 # Zookeeper Setup and Configuration
 #---------------------------------------------------------
@@ -126,8 +139,27 @@ zookeeper_client_port=2181
 
 setup_zookeeper() {
 
-    #TODO... put in zookeeper install check
-    
+    echo -n "Checking for zookeeper ${zookeeper_version}... "
+    [ -x ${zookeeper_install_dir}/bin/zkServer.sh ] && check_zookeeper_version
+    [ $? == 0 ] && (( ! force_install )) && echo " [OK]" && return 0
+
+    echo
+    echo "*******************************"
+    echo "Setting up Zookeeper... ${zookeeper_version}"
+    echo "*******************************"
+    echo
+
+    local dosetup
+    if [ -x ${zookeeper_install_dir}/bin/zkServer.sh ]; then 
+        echo "Detected an existing zookeeper installation..."
+        read -p "Do you want to continue with zookeeper installation and setup? [y/N] " dosetup
+        if [ "${dosetup}" != "Y" ] && [ "${dosetup}" != "y" ]; then
+            echo "Skipping zookeeper installation and setup - will assume zookeeper is setup properly"
+            return 0
+        fi
+        echo
+    fi
+
     echo "Installing zookeeper v${zookeeper_version}"
     mkdir -p ${zookeeper_workdir}
     pushd ${zookeeper_workdir} >& /dev/null
@@ -185,7 +217,18 @@ setup_zookeeper() {
     return 0
 }
 
+#Helper Method to figure out the version of Zookeeper running
+check_zookeeper_version() {
+    #NOTE: This would have been much sexier with sed and probably in one line... 
+    #but my sed is a bit weak at the moment. :-(
+    local f=$(/bin/ls ${zookeeper_install_dir} | egrep '^zookeeper.*jar$')
+    f=${f%*.jar}
+    f=${f#*-}
+    [ "${f}" = "${zookeeper_version}" ]
+}
+
 configure_zookeeper() {
+    echo "configuring zookeeper... "
     pushd ${zookeeper_install_dir}
     export ZK_DIR=${zookeeper_install_dir} #NOTE: Is this a special variable used by zookeeper? If not get rid of line.
 
@@ -196,13 +239,17 @@ configure_zookeeper() {
     sha1sum <(echo esgf$(hostname -i)) | awk '{print $1}' > ${zookeeper_data_dir}/myid
     echo "zookeeper id: $(cat ${zookeeper_data_dir}/myid)"
     popd >& /dev/null
-    echo "zookeeper configuration [OK]"
+    echo " [OK]"
     return 0
 }
 
 test_zookeeper() {
+    echo -n "Testing zookeeper..."
     #test client connection
     ${zookeeper_install_dir}/bin/zkCli.sh -server localhost:2181 ls / quit
+    ret=$?
+    [ ${ret} == 0 ] && echo " [OK]" || echo " [FAIL]"
+    return ${ret}
 }
 
 write_zookeeper_install_log() {
@@ -235,6 +282,7 @@ start_zookeeper() {
 }
 
 stop_zookeeper() {
+    echo "Stopping zookeeper..."
     ${zookeeper_install_dir}bin/zkServer.sh stop
 }
 #---------------------------------------------------------
