support for building in devel location

diff --git a/bin/post b/bin/post
--- a/bin/post
+++ b/bin/post
@@ -62,15 +62,35 @@
 
 #uses: egrep, rsync (and thus ssh)
 
-debug=${debug:-0}
+devel=${devel:-0}
+verbose=${verbose:-0}
 noop=${noop:-0}
 
-((debug)) && echo "Debug is ON"
-((noop)) && echo "Noop is ON"
+while [ -n "$1" ]; do 
+    case $1 in
+        --devel)
+            devel=1
+            ;;
+        --verbose)
+            verbose=1
+            ;;
+        --noop | --dry-run)
+            noop=1
+            ;;
+        *)
+	    printf "\n ERROR: unknown switch \"$1\" \n\n" && exit 1
+	    ;;
+    esac
+    shift
+done
+
+((devel)) && echo "Pushing to development area..."
+((verbose)) && echo "Verbose is ON"
+((noop)) &&  echo "Noop is ON"
 
 manifest_file=${manifest_file:-$0.manif}
-esg_dist_url="rainbow.llnl.gov:/pcmdi_web/dist"
-current_dir=${current_dir:="esg_node"}
+esg_dist_url="rainbow.llnl.gov:/pcmdi_web/dist$( ((devel == 1)) && echo "/devel" || echo "")"
+current_dir=${current_dir:="esg-search"}
 xfer_user=${xfer_user:-""}
 
 [ -n "${xfer_user}" ] && xfer_user+="@" && echo "[${xfer_user}${esg_dist_url}]"
@@ -78,19 +98,6 @@ xfer_user=${xfer_user:-""}
 fail=0
 good=0
 total=0
-
-while [ -n "$1" ]; do 
-    case $1 in
-        --debug)
-            shift
-            debug=1
-            ;;
-        --dry-run|--noop)
-            shift
-            noop=1
-            ;;
-    esac
-done
 
 while read file dest_dir; do
     
@@ -108,7 +115,7 @@ while read file dest_dir; do
 
     if [ ! -e $file ]; then
 	echo -n "x"
-	((debug)) && echo " [FAIL] No Such File $file"
+	((verbose)) && echo " [FAIL] No Such File $file"
 	((++total))
 	((++fail))
 	continue
@@ -117,16 +124,16 @@ while read file dest_dir; do
     dest_dir=${dest_dir:-"${current_dir}"}
     #echo "[$file] >> [$dest_dir]"
     
-    ((debug)) && echo -n "pushing $file ---> ${xfer_user}${esg_dist_url}/${dest_dir} " || echo -n "*"
+    ((verbose)) && echo -n "pushing $file ---> ${xfer_user}${esg_dist_url}/${dest_dir} " || echo -n "*"
     ((!noop))  && md5sum $file > ${file}.md5
     ((!noop))  && rsync -c ${file}.md5 ${xfer_user}${esg_dist_url}/${dest_dir}/${file##*/}.md5 >& /dev/null
     echo -n "-"
     ((!noop))  && rsync -c ${file} ${xfer_user}${esg_dist_url}/${dest_dir}/${file##*/} >& /dev/null
     if [ $? != 0 ]; then
-	((debug)) && echo "[FAIL]"
+	((verbose)) && echo "[FAIL]"
 	((++fail))
     else
-	((debug)) && echo "[OK]" 
+	((verbose)) && echo "[OK]" 
 	((++good))
     fi
     ((++total))
