New flag -C added to enable the download of data using cookies.

diff --git a/etc/conf/wget-template b/etc/conf/wget-template
--- a/etc/conf/wget-template
+++ b/etc/conf/wget-template
@@ -42,6 +42,9 @@ COOKIE_JAR=$ESG_HOME/cookies
 MYPROXY_GETCERT=$ESG_HOME/getcert.jar
 CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)
 
+WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates
+
+
 # Configure checking of server SSL certificates.
 #   Disabling server certificate checking can resolve problems with myproxy
 #   servers being out of sync with datanodes.
@@ -127,7 +130,7 @@ debug=0
 clean_work=1
 
 #parse flags
-while getopts ':c:pfF:o:w:isuUndvqh' OPT; do
+while getopts ':c:pfF:o:w:isuUndvqhC' OPT; do
     case $OPT in
         c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
         p) clean_work=0;;               #       : preserve data that failed checksum
@@ -143,7 +146,8 @@ while getopts ':c:pfF:o:w:isuUndvqh' OPT; do
         d) verbose=1;debug=1;;          #       : display debug information
         v) verbose=1;;                  #       : be more verbose
         q) quiet=1;;                    #       : be less verbose
-        h) usage && exit 0;;            #       : displays this help
+        C) skip_security=1 && use_cks=1;; #      : Do not use certificates for security but use cookies
+        h) usage && exit 0;;           #       : displays this help
         \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
         \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
     esac
@@ -425,6 +429,150 @@ remove_from_cache() {
     unset cached
 }
 
+#Download data from node using cookies and not certificates.
+download_using_cookies()
+{
+  #The data to be downloaded.
+  data=" $url"
+  filename="$file"  
+
+  #Wget args.
+  if ((insecure)) 
+  then
+   wget_args=" --no-check-certificate --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt --load-cookies $COOKIES_FOLDER/wcookies.txt " 
+  else
+   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt --load-cookies $COOKIES_FOLDER/wcookies.txt "  
+  fi 
+   
+ 
+  #Try to download the data. 
+  command="wget $wget_args $data"
+  http_resp=$(eval $command  2>&1) 
+    
+    
+  #Evaluate response.
+  if ( echo "$http_resp" | grep -q " 302 " )  
+  then
+   urls=$(echo $http_resp | egrep -o 'https?://[^ ]+'| cut -d'/' -f 3)
+   orp_service=$(echo $urls | cut -d' ' -f 3)
+   if [ -n "$orp_service" ] 
+   then
+    orp_service_found=1
+   else
+    orp_service_found=0
+   fi
+  else
+   orp_service_found=0
+  fi
+ 
+  #If redirected to orp service send the openid. 
+  if [[ orp_service_found -eq 1 ]]
+  then
+
+   
+   #Download data using either basic auth or login form
+   if [[ $openid_c == *esgf-idp/openid/ ]]
+   then
+    download_data_open_id
+   else
+    download_data_cl_id
+   fi
+  else
+   if ( ( echo "$http_resp" | grep -q "401 Unauthorized" ) || ( echo "$http_resp" | grep -q "403: Forbidden" ) ||  ( echo "$http_resp" | grep -q "Connection timed out." ) )
+   then 
+    echo "ERROR : http request to orp service did not send."
+    failed=1
+   fi
+  fi
+}
+
+#Function for downloading data using the claimed id.
+download_data_cl_id()
+{
+  #Http request for senting openid to the orp service.
+  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args  https://$orp_service/esg-orp/j_spring_openid_security_check.htm "
+
+ 
+  #Execution of command.
+  http_resp=$(eval $command  2>&1)
+   
+  #Evaluate response.
+  if (  ( echo "$http_resp" | grep -q " 302 " ) && ( echo "$http_resp" | grep -q "login.htm" ) )  
+  then
+   urls=$(echo $http_resp | egrep -o 'https?://[^ ]+' | cut -d'/' -f 3)
+   idp_service=$(echo $urls | cut -d' ' -f 2) 
+   if [[ -n "$idp_service" ]] 
+   then
+    idp_service_found=1
+   else
+    idp_service_found=0
+   fi
+  else
+   idp_service_found=0
+  fi
+
+  #If redirected to idp service send the credentials.
+  if [[ idp_service_found -eq 1 ]]   
+  then
+            
+   command="wget --post-data  \"password=$password_c\" $wget_args -O $filename https://$idp_service/esgf-idp/idp/login.htm"
+              
+   #Execution of command.
+   http_resp=$(eval $command  2>&1)
+          
+   if ( ( echo "$http_resp" | grep -q "text/html" ) || ( echo "$http_resp" | grep -q "403: Forbidden" ) )  
+   then 
+    failed=1;
+    rm $filename  
+   fi
+ 
+  else
+   echo "ERROR : http request to idp service did not send."
+   failed=1
+  fi #if redirected to idp.  
+}
+
+
+
+download_data_open_id()
+{
+  #Http request for senting openid to the orp web service.
+  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  --header=\"Agent-type:cl\" --http-user=$username_c --http-password=$password_c    $wget_args  -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "
+
+  
+  #Execution of command.
+  http_resp=$(eval $command  2>&1)
+  
+  redirects=$(echo $http_resp | egrep -o ' 302 ')
+  
+  #Last redirect indicating that file has been reached.
+  file_downloaded=$(echo $redirects | cut -d' ' -f 7) 
+         
+    
+  #Evaluate response.
+  if ( echo "$http_resp" | grep -q "text/html" )  
+  then
+   idp_service_found=0
+  else
+   idp_service_found=1
+  fi  
+    
+  if [[ -z "$file_downloaded" ]] 
+  then
+   idp_service_found=0
+  else
+   idp_service_found=1     
+  fi  
+      
+       
+  if [[ $idp_service_found -ne 1 ]] 
+  then 
+   failed=1;
+   rm $filename        
+  fi
+}
+
+
 download() {
     wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c $PKI_WGET_OPTS"
     
@@ -473,7 +621,16 @@ download() {
                 #No status will be stored
                 break
             else
-                $wget -O "$file" $url || { failed=1; break; }
+                if ((use_cks))
+                then
+                 download_using_cookies $openid_c $password_c $file $url 
+                 if ((failed))
+                 then
+                  break
+                 fi
+                else
+                 $wget -O "$file" $url || { failed=1; break; }  
+                fi                
             fi
 
             #check if file is there
@@ -567,6 +724,29 @@ sleep 1
 
 check_os
 ((!skip_security)) && find_credentials
+
+if ((use_cks))
+then 
+     
+ if (( ! insecure))
+  then 
+   get_certificates
+ fi
+
+ #Create cookies folder.
+ COOKIES_FOLDER="$ESG_HOME/wget_cookies"
+ if [[ ! -d $COOKIES_FOLDER ]] 
+  then
+   mkdir $COOKIES_FOLDER
+ fi
+  
+ read -p    "Enter your openid : " openid_c
+ read -p    "Enter username (if not supplied within openid) : " username_c
+ read -s -p "Enter password : " password_c
+ echo -e "\n"
+fi 
+
+
 #do we have old results? Create the file if not
 [ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE
 
@@ -576,4 +756,19 @@ unset force
 download
 
 dedup_cache_
+
+#Clean up temp data.
+if ((use_cks))
+then 
+ if [ -f "j_spring_openid_security_check.htm" ] 
+ then
+  rm j_spring_openid_security_check.htm
+ fi
+
+ if [ -d $COOKIES_FOLDER ] 
+  then
+   rm -rf $COOKIES_FOLDER
+ fi
+fi
+
 echo "done"
