update wget-template to bring down esg-truststore to fix issue with java not strusting esgf-cas

diff --git a/etc/conf/wget-template b/etc/conf/wget-template
--- a/etc/conf/wget-template
+++ b/etc/conf/wget-template
@@ -238,6 +238,11 @@ get_certificates() {
     # don't if this was already done today
     [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
     echo -n "Retrieving Federation Certificates..." >&2
+
+    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
+        echo "Could not fetch esg-truststore";
+        return 1
+    fi
     
     if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
         #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
